name: mobile_hydromelon
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.4.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  get: 4.6.6
  http: ^1.2.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: 5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-Light.ttf
          weight: 200
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-Black.ttf
          weight: 900

flutter_gen:
  output: lib/apps/gen

dependency_overrides:
  dart_style: 2.2.4
